#!/usr/bin/env bash

cowsay "Installing Java !"
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer

echo  >> ~/.bashrc
echo '# Adding JAVA_HOME ' >> ~/.bashrc 
JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))/

echo export JAVA_HOME=$JAVA_HOME >> ~/.bashrc 
cowsay Java Installed at $JAVA_HOME 
