#!/usr/bin/env bash

# my server installation script
# atleat needs git

echo Hello $USER.... Your system is :
uname -a
 
echo "Now we start installing all you want!"
cd

echo "Upgrading system"
sudo apt-get update
sudo apt-get upgrade

echo "Installing Basic Linux requirements for You !"

sudo apt-get install cowsay gdebi-core language-pack-en-base build-essential
#Just to make sure locale settings are proper
sudo dpkg-reconfigure locales 

mkdir ~/dwnls

java-setup
python-setup
r-setup
xgb-setup
vim-setup
emacs-setup
aliases-setup

coway "I believe your whole stack has been Completed. In Case you need more please do it manually"
