#!/usr/bin/env bash

cowsay "Setting up your Vim for python"
cd dwnls
git clone https://github.com/vim/vim.git
cd vim/src 
vi_cv_path_python=$HOME/anaconda2/bin/python ./configure --with-features=huge --enable-pythoninterp=yes --prefix=$HOME/vim-py-ide
make && make check && make install && make clean
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
cp remote-setup/vimrc ~/.vimrc

cowsay "Now Setting Vim for Python development"
vim +PluginInstall +qall

cd
